id = "wakfu-theme"
name = "Wakfu Theme"
description = "Wakfu Theme for Zed"
version = "0.1.1"
schema_version = 1
authors = ["Jules Sorensen <julessorens@gmail.com>"]
repository = "https://github.com/JulesSorensen/zed-wakfu-theme"
